l9/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :todos

  resources :users

  # The user session can be treated as a singular resource.
  # Learn more about these here: https://guides.rubyonrails.org/routing.html#singular-resources
  resource :session

  root to: "home#index"
end

l9/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

l9/app/models/todo.rb
class Todo < ApplicationRecord
  validates :todo_text, presence: :true, length: { minimum: 2 }
  validates :due_date, presence: :true

  belongs_to :user

  def due_today?
    @due_date == Date.today
  end

  def self.overdue
    where("due_date < ? and completed = ?", Date.today, false)
  end

  def self.due_today
    where("due_date = ?", Date.today)
  end

  def self.due_later
    where("due_date > ?", Date.today)
  end

  def self.completed
    all.where(completed: true)
  end
end

l9/app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :email, presence: true

  has_secure_password

  has_many :todos
end

l9/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_is_signed_in

  def ensure_user_is_signed_in
    unless current_user
      redirect_to root_path
    end
  end

  def current_user
    return @current_user if instance_variable_defined?(:@current_user)

    current_user_id = session[:current_user_id]
    @current_user = current_user_id ? User.find(current_user_id) : nil
  end
end

l9/app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_is_signed_in

  def index
    if current_user.present?
      redirect_to todos_path
    else
      render "index"
    end
  end
end

l9/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_is_signed_in, only: [:new, :create]

  # POST /session
  def create
    user = User.find_by(email: params[:email])

    if user.present? && user.authenticate(params[:password])
      flash[:notice] = "You are now signed in."
      session[:current_user_id] = user.id
      redirect_to todos_path
    else
      flash[:error] = "We're sorry, but we could not verify your credentials."
      redirect_to new_session_path
    end
  end

  # DELETE /session
  def destroy
    session[:current_user_id] = nil
    flash[:notice] = "You have successfully signed out."
    redirect_to root_path
  end
end

l9/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  # GET /todos
  def index
    @todos = current_user.todos
    render "index"
  end

  # POST /todos
  def create
    todo_text = params[:todo_text]
    due_date = Time.zone.parse(params[:due_date])

    todo = current_user.todos.new(
      todo_text: todo_text,
      due_date: due_date,
      completed: false,
    )

    if todo.save
      flash[:notice] = "A new to-do has been added."
      redirect_to todos_path
    else
      flash[:error] = "Encountered errors: #{todo.errors.full_messages.join(", ")}"
      redirect_to new_todo_path
    end
  end

  # PATCH /todos/:id
  def update
    id = params[:id]
    completed = params[:completed]

    todo = Todo.find(id)
    todo.completed = completed
    todo.save!

    redirect_to todos_path
  end

  # DELETE /todos/:id
  def destroy
    id = params[:id]

    todo = Todo.find(id)
    todo.destroy!

    redirect_to todos_path
  end
end

l9/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_is_signed_in

  # POST /users
  def create
    if User.exists?(email: params[:email])
      flash[:error] = "There is already an account with that email. Sign in instead."
      redirect_to new_session_path
      return
    end

    user = User.new(first_name: params[:first_name], last_name: params[:last_name], email: params[:email], password: params[:password])

    if user.save
      flash[:notice] = "You have successfully signed up."
      session[:current_user_id] = user.id
      redirect_to root_url
    else
      flash[:error] = user.errors.full_messages.join(", ")
      redirect_to new_user_path
    end
  end
end

l9/app/helpers/application_helper.rb
module ApplicationHelper
end

l9/app/views/home/index.html.erb
<h1 class="Header-title">Just Another To-do Manager</h1>
<hr>
<ol class="Home-authenticate">
  <li>If you are a new user, <%= link_to "sign up", new_user_path %>.</li>
  <li>If you are an existing user, <%= link_to "sign in", new_session_path %>.</li>
</ol>

l9/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>To-do Manager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <% flash.each do |type, message| %>
      <p class="<%= "Flash Flash-#{type}" %>">
        <%= message %>
      </p>
    <% end %>
    <% if @current_user.present? %>
      <div class="UserHeader">
        Hello, <%= @current_user.first_name %>
        <%= button_to 'Sign Out', session_path, method: :delete, class: 'UserHeader-button' %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

l9/app/views/todos/_todo-section.html.erb
<section class="TodoSection">
  <div class="TodoSectionTitle">
    <p class="TodoSectionTitle-text"><%= section_title %></p>
    <p class="TodoSectionTitle-remainingCount"><%= todos.completed.count %> / <%= todos.count %></p>
  </div>
  <ul>
    <% todos.each do |todo| %>
      <li class="TodoItem">
        <label class="TodoItem-container">
          <%= form_with(url: "/todos/#{todo.id}", method: "put") do %>
            <%= check_box_tag(:completed, :completed, todo.completed, class: "TodoItem-checkbox", onclick: "this.form.submit()") %>
          <% end %>
          <p class="TodoItem-text <%= todo.completed ? 'TodoItem-text--completed': nil %>">
            <%= todo.todo_text %>
          </p>
          <% if show_due_date %>
            <p class="TodoItem-dueDate"><%= todo.due_date.to_fs(:short) %></p>
          <% end %>
          <%= form_with(url: "/todos/#{todo.id}", method: "delete") do %>
            <%= image_submit_tag("/trashcan.png", alt: "delete", class: "TodoItem-delete") %>
          <% end %>
        </label>
      </li>
    <% end %>
  </ul>
</section>

l9/app/views/todos/index.html.erb
 <main class="TodoPageMain">
  <h2 class="TodoPage-title">My To-do List</h2>
  <%= form_with(url: "/todos" ,methods: "post", class: "AddTodo" ) do %>
    <%= text_field_tag(:todo_text, nil, placeholder: "What's next?", class: "AddTodo-text", :required => true) %>
    <%= date_field_tag(:due_date, nil, class: "AddTodo-date", :required => true)%>
    <%= submit_tag("Add", class: "AddTodo-button") %>
  <% end %>
  <%= render partial: "todo-section",
    locals:{
      section_title: "Overdue",
      todos: @todos.overdue,
      show_due_date: true
        } %>
  <%= render partial: "todo-section",
    locals:{
      section_title: "Due Today",
      todos: @todos.due_today,
      show_due_date: false
    } %>
  <%= render partial: "todo-section",
    locals:{
      section_title: "Due later",
      todos: @todos.due_later,
      show_due_date: true
    } %>
</main>

l9/app/views/users/new.html.erb
<h1 class="Header-title">Hello, stranger!</h1>
<hr>
<section>
  <%= form_with url: users_path do |form| %>
    <div class="Form-group">
      <%= form.label :first_name, 'First Name', class: "Form-label" %>
      <%= form.text_field :first_name, class: "Form-input" %>
    </div>
    <div class="Form-group">
      <%= form.label :last_name, 'Last Name', class: "Form-label" %>
      <%= form.text_field :last_name, class: "Form-input" %>
    </div>
    <div class="Form-group">
      <%= form.label :email, 'Email', class: "Form-label" %>
      <%= form.email_field :email, class: "Form-input" %>
    </div>
    <div class="Form-group">
      <%= form.label :password, 'Password', class: "Form-label" %>
      <%= form.password_field :password, class: "Form-input" %>
    </div>
    <div class="Form-group">
      <%= form.submit "Sign up", class: "Form-submit" %>
    </div>
  <% end %>
  <hr>
  <p>Would you like to <%= link_to 'sign in', new_session_path %> instead?</p>
</section>